# coding: utf-8

# flake8: noqa

"""
    Strava API v3

    The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from strava_swagger.api.activities_api import ActivitiesApi
from strava_swagger.api.athletes_api import AthletesApi
from strava_swagger.api.clubs_api import ClubsApi
from strava_swagger.api.gears_api import GearsApi
from strava_swagger.api.routes_api import RoutesApi
from strava_swagger.api.running_races_api import RunningRacesApi
from strava_swagger.api.segment_efforts_api import SegmentEffortsApi
from strava_swagger.api.segments_api import SegmentsApi
from strava_swagger.api.streams_api import StreamsApi
from strava_swagger.api.uploads_api import UploadsApi
# import ApiClient
from strava_swagger.api_client import ApiClient
from strava_swagger.configuration import Configuration
# import models into sdk package
from strava_swagger.models.activity_stats import ActivityStats
from strava_swagger.models.activity_total import ActivityTotal
from strava_swagger.models.activity_type import ActivityType
from strava_swagger.models.activity_zone import ActivityZone
from strava_swagger.models.altitude_stream import AltitudeStream
from strava_swagger.models.base_stream import BaseStream
from strava_swagger.models.cadence_stream import CadenceStream
from strava_swagger.models.comment import Comment
from strava_swagger.models.detailed_activity import DetailedActivity
from strava_swagger.models.detailed_athlete import DetailedAthlete
from strava_swagger.models.detailed_club import DetailedClub
from strava_swagger.models.detailed_gear import DetailedGear
from strava_swagger.models.detailed_segment import DetailedSegment
from strava_swagger.models.detailed_segment_effort import DetailedSegmentEffort
from strava_swagger.models.distance_stream import DistanceStream
from strava_swagger.models.error import Error
from strava_swagger.models.explorer_response import ExplorerResponse
from strava_swagger.models.explorer_segment import ExplorerSegment
from strava_swagger.models.fault import Fault
from strava_swagger.models.heart_rate_zone_ranges import HeartRateZoneRanges
from strava_swagger.models.heartrate_stream import HeartrateStream
from strava_swagger.models.lap import Lap
from strava_swagger.models.lat_lng import LatLng
from strava_swagger.models.lat_lng_stream import LatLngStream
from strava_swagger.models.meta_activity import MetaActivity
from strava_swagger.models.meta_athlete import MetaAthlete
from strava_swagger.models.meta_club import MetaClub
from strava_swagger.models.moving_stream import MovingStream
from strava_swagger.models.photos_summary import PhotosSummary
from strava_swagger.models.polyline_map import PolylineMap
from strava_swagger.models.power_stream import PowerStream
from strava_swagger.models.power_zone_ranges import PowerZoneRanges
from strava_swagger.models.route import Route
from strava_swagger.models.route_direction import RouteDirection
from strava_swagger.models.running_race import RunningRace
from strava_swagger.models.segment_leaderboard import SegmentLeaderboard
from strava_swagger.models.segment_leaderboard_entry import SegmentLeaderboardEntry
from strava_swagger.models.smooth_grade_stream import SmoothGradeStream
from strava_swagger.models.smooth_velocity_stream import SmoothVelocityStream
from strava_swagger.models.split import Split
from strava_swagger.models.stream_set import StreamSet
from strava_swagger.models.summary_activity import SummaryActivity
from strava_swagger.models.summary_athlete import SummaryAthlete
from strava_swagger.models.summary_club import SummaryClub
from strava_swagger.models.summary_gear import SummaryGear
from strava_swagger.models.summary_segment import SummarySegment
from strava_swagger.models.summary_segment_effort import SummarySegmentEffort
from strava_swagger.models.temperature_stream import TemperatureStream
from strava_swagger.models.time_stream import TimeStream
from strava_swagger.models.timed_zone_distribution import TimedZoneDistribution
from strava_swagger.models.timed_zone_range import TimedZoneRange
from strava_swagger.models.updatable_activity import UpdatableActivity
from strava_swagger.models.upload import Upload
from strava_swagger.models.zone_range import ZoneRange
from strava_swagger.models.zone_ranges import ZoneRanges
from strava_swagger.models.zones import Zones
